apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-client
  labels:
    app: nginx-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-client
  template:
    metadata:
      labels:
        app: nginx-client
    spec:
      containers:
        - name: nginx-client
          image: gnunu/nginx-client-openssl
          ports:
          - containerPort: 443
          env:
          - name: NGINX_SERVICE_NAME
            value: nginx-server
          - name: MODE
            value: https
          - name: PROTOCOL
            value: TLSv1.3
          - name: CERT
            value: rsa2048
          - name: CIPHER
            value: AES128-GCM-SHA256
          - name: GETFILE
            value: index.html
          - name: REQUEST
            value: 100000000
